### ISSUE TITLE
Uncaught TypeError: Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by 3nt3** [malaire/elm-dependencies-analyzer#5]
when trying to use the analyzer the console is flooded with this message (thousands of times)

![2021-06-12-145303_1850x250_scrot](https://user-images.githubusercontent.com/39235738/121776598-0f743280-cb8e-11eb-9e19-ea2e43097eb2.png)

**Comment by malaire** [comment]
That is common error with Elm when you have some browser extension which modifies the web page.

Can you try with browser extensions disabled to confirm that this is caused by a browser extension?

**Comment by 3nt3** [comment]
It works when disabling the "Dark Reader" extension
